language: node_js
sudo: false
node_js:
  - lts/dubnium
  - node
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: JYwdA6NJp19PaPgOTzI/7yrc57vhiIpGwTusPgTSiDFVb5TQ9JWU74Elurx9BhhjWYrNW4LdgrXQDEQW0UL8T8oAZqW5APYfuKysFNztaz0sb2Si4KjIFBsP4vu8r5wZ+5W8Ju6AT6IuaYkxqWV9r9hZ6Lc9zWbcgl6tXGZgfqU=
  file:
    - 'buzzwords.js'
    - 'buzzwords.min.js'
  on:
    tags: true
