export var buzzwords = [
  '4g',
  '5g',
  'accountable talk',
  'agile',
  'эджайл',
  'аджайл',
  'ajax',
  'algorithm',
  'алгоритм',
  'alignment',
  'ambiguity',
  'amplify',
  'analytics',
  'аналитика',
  'andon',
  'api',
  'апи',
  'artisan',
  'at the end of the day',
  'back-end',
  'backend',
  'бэкенд',
  'бэк-енд',
  'ballpark figure',
  'bandwidth',
  'пропускной канал',
  'benchmarking',
  'бенчмаркинг',
  'best of breed',
  'best practices',
  'лучшие практики',
  'beta',
  'бета',
  'big data',
  'биг дата',
  'big society',
  'bio-',
  'bizmeth',
  'bleeding edge',
  'blockchain',
  'блокчейн',
  "bloom's taxonomy",
  'break through the clutter',
  'brick-and-mortar',
  'bricks-and-clicks',
  'bring to the table',
  'bring your own device',
  'building capabilities',
  'business process outsourcing',
  'business-to-business',
  'b2b',
  'b2c',
  'би ту би',
  'би ту си',
  'business-to-consumer',
  'buzzword',
  'buzzword compliant',
  'cadence',
  'catchphrase',
  'clear goal',
  'clickthrough',
  'client-centric',
  'close the loop',
  'cloud-computing',
  'облачные',
  'облачный',
  'облако',
  'cloud-based',
  'co-opetition',
  'collaboration',
  'come-to-jesus moment',
  'common core',
  'контент',
  'история',
  'стори',
  'content management',
  'content management system',
  'content marketing',
  'convergence',
  'core competency',
  'corporate jargon',
  'coward',
  'creative',
  'креатив',
  'cross-platform',
  'css3',
  'customer-centric',
  'cyber-physical systems',
  'data mining',
  'data science',
  'дата',
  'datafication',
  'deep dive',
  'deep learning',
  'deep web',
  'design pattern',
  'devops',
  'девопс',
  'differentiated instruction',
  'digital divide',
  'digital literacy',
  'digital remastering',
  'digital rights management',
  'digital signage',
  'цифровой',
  'цифр',
  'релок',
  'disruptive innovation',
  'disruptive technologies',
  'diversity',
  'document management',
  'dot-bomb',
  'downsizing',
  'drill down',
  'drinking the kool-aid',
  'e-learning',
  'ремоут',
  'дистанционно',
  'early-stage',
  'ранний',
  'eating your own dogfood',
  'eco-',
  'эко',
  'emotional intelligence',
  'employer branding',
  'empowerment',
  'enable',
  'end-to-end',
  'end to end',
  'engine',
  'движок',
  'enterprise',
  'энтерпрайз',
  'энтепрайз',
  'enterprise content management',
  'enterprise service bus',
  'entitlement',
  'ephemeral rogue entity',
  'establishment',
  'эстеблишмент',
  'евангелист',
  'evangelist',
  'event horizon',
  'exit strategy',
  'eyeballs',
  'face time',
  'facial recognition',
  'fit for purpose',
  'fleet dynamism',
  'flipped classroom',
  'folksonomy',
  'framework',
  'фреймворк',
  'free value',
  'frictionless',
  'front-end',
  'front end',
  'frontend',
  'фронтэнд',
  'fulfilment issues',
  'fuzzy logic',
  'generation x',
  'generation y',
  'globalization',
  'going forward',
  'grow',
  'рост',
  'growth hacking',
  'guided reading',
  'headlights',
  'heavy lifting',
  'herding cats',
  'higher-order thinking',
  'holistic',
  'holistic approach',
  'home',
  'html5',
  'hype cycle',
  'hyperlocal',
  'iaas',
  'ideation management',
  'immersion',
  'impact',
  'information society',
  'information superhighway',
  'innovation',
  'innovative',
  'инновационный',
  'инновации',
  'instructional scaffolding',
  'internet of things',
  'invested in',
  'javascript',
  'knowledge process outsourcing',
  'lambda',
  'lateral violence',
  'law of the instrument',
  'leverage',
  'list of buzzwords',
  'logistics',
  'логистика',
  'бизнес',
  'процессы',
  'long tail',
  'low hanging fruit',
  'machine learning',
  'make it pop',
  'management visibility',
  'marketing buzz',
  'mashup',
  'memetics',
  'microservices',
  'микросервисы',
  'микросервисная',
  'архитектура',
  'millennial',
  'миллениал',
  'mind share',
  'mindshare',
  'mission critical',
  'mobile',
  'modularity',
  'модуль',
  'mouthfeel',
  'moving forward',
  'multiple intelligences',
  'nanotechnology',
  'national security',
  'netiquette',
  'new economy',
  'new normal',
  'next generation',
  'поколение',
  'offshoring',
  'on the runway',
  'one team',
  'open source',
  'опенсорс',
  'opensource',
  'opportunities',
  'optics',
  'organic growth',
  'органический',
  'paas',
  'pain point',
  'paradigm',
  'парадигма',
  'paradigm shift',
  'paralysis by analysis',
  'passionate',
  'pleonasm',
  'podcast',
  'подкаст',
  'political capital',
  'power word',
  'privacy',
  'proactive',
  'проактив',
  'productivity',
  'продуктив',
  'продукт',
  'profit center',
  'project-based learning',
  'psychobabble',
  'push the envelope',
  'quantum supremacy',
  'quick win',
  'reach out',
  'real-time',
  'realtime',
  'reimagine',
  'resonate',
  'responsive web design',
  'return on investment',
  'reverse fulfilment',
  'rightshoring',
  'roadmap',
  'road-map',
  'дорожная карта',
  'robust',
  'run like a business',
  'rustic',
  'saas',
  'scalability',
  'sea change',
  'seamless',
  'sensorization',
  'serum',
  'share options',
  'single pane-of-glass',
  'sisterhood',
  'skeuomorphic',
  'social bookmarking',
  'social software',
  'software defined networking',
  'solidarity',
  'solution',
  'решение',
  'эффективность',
  'sox',
  'spa',
  'spam',
  'спам',
  'spin-up',
  'stack',
  'stakeholder',
  'startup',
  'start-up',
  'стартап',
  'storytelling',
  'стори',
  'strategic communication',
  'strategic ineptness',
  'стратег',
  'streamline',
  'student engagement',
  'survival strategy',
  'sustainability',
  'sync-up',
  'synergy',
  'systems development life-cycle',
  'tagging',
  'take offline',
  'talent relationship management',
  'think outside the box',
  'tiger team',
  'time-blindness',
  'toolchain',
  'touchpoint',
  'transmedia',
  'unpack',
  'user generated content',
  'ugc',
  'value add',
  'ценность',
  'value-added',
  'viral',
  'виральн',
  'virtualization',
  'виртуальн',
  'virtue word',
  'visibility',
  'vortal',
  'warfighter',
  'water under the bridge',
  'weasel word',
  'web 2.0',
  'web services',
  'webinar',
  'wellness',
  'wheelhouse',
  'wikiality',
  'win-win',
  'work smarter',
  'workflow',
  'воркфлоу'
]
